### ISSUE TITLE
The ILAMB priorities list

### ISSUE THREAD

**Issue by dvalters** [GCEL/ILAMB#15]
## This 'master' issue is to collate, discuss, and prioritise the remaining tasks for the ILAMB/CSSP project at the end of March. 

 - [x] ILAMB workshop/tutorial for Tuesday 12th February (2 hours max)

### Immediate fixes:

 - [x] Resolve the masks issue and re-run to test this works. 
   - [x] Improve the documentation of how this works. 
 - [x] Add variables to the config file and re-run once metadata is fixed.
   - [x] Expand the documentation for other users of this config file. 

### Functionality Enhancements (priority)

 - [ ] Uncertainty stippling with CARDAMOM. See #22. 
   - [ ] It would also be good to add uncertainty also to the seasonal cycles - but that is scientifically harder as it requires an aggregation of CARDAMOM uncertainty.
 - [ ] Functional response plots (already exists in code, just needs a bit more documentation and experimentation with our datasets first.
 - [ ] Coastline trimming on plots (JULES?) 
   - [ ] Control over interpolation method used to do plots. i.e. simple bilinear or cubic interpolation for smoothing?

### Minor Issues (some of these are data processing, rather than software development, related)

 - [ ] Explanation of what the relative scores are (compared to absolute)
   - nice if we could click a hyperlink from the outputs that took us to to explanations or formulas.
 - [ ] Link back to the results table page from variable pages. (or someway of getting back) Issue #21, WIP #19.
 - [x] **Fix the date issue! (days since 1850...)** See #9 
 - [ ] Expansion of values to go in the Taylor diagram
 - [x] Why are the bias values so low? (Fixed in #9 - minor limit bug)
 - [ ] Can we force a colour bar data limit in the VegRT, but not other plots? (Current hacky workaround is to temporarily hard code this in the ILAMB code, but it would be nice if we could, say, override it in the ILAMB config file, much like we can for the colour map.) See #18. 
 -  [ ] Strange stats values persist in the veg RT pages, possibly data-related as other plots seem to have more reasonable numbers.

 - [ ] Get the response function tool working (i.e. plotting C variables against climate)
 - [ ] Adding other variables, like LAI, C pools, CUE, allocation to various tissues and their turnovers.

### Later tasks:

 - [ ]  Add more comparison datasets (i.e. Benchmarks) in addition to CARDAMOM.)
 - [ ] Export web page figures to publication-quality outputs. See #4

**Comment by dvalters** [comment]
Also: Scale on 'difference in max month' is also rather too large to allow useful analysis.
